### PR TITLE
Allow config charset database.

### PR DESCRIPTION
**Pull request by tonynguyen68**

### CODE REVIEW

**Comment by tonynguyen68** [comment]
Sorry for missing, I have another pull request that have config key.

**Comment by sergeyklay** [comment]
@dschissler Could you please take a look

**Comment by dschissler** [comment]
@sergeyklay It will be 1-2 days before I can look.

**Comment by dschissler** [comment]
I think that in the Dev Tools templates that someone added some code to unset the charset if it is a Postgres database.  I don't particularly like that it is done that way but there might be a reason for it.  Does anyone know?

**Comment by sergeyklay** [comment]
Yes, I think so. Here may be an issue with Postgres

**Comment by ch3k1** [comment]
Hi @sergeyklay , If applications require data storage using a different character set or collation, you can configure character set with  ``` 'charset' => 'utf8'```  without it different character not works, if you want different  character without vokuro config, you can Configure initial settings 

### add follows within [mysqld] section
```
character-set-server=utf8
collation-server=utf8_general_ci
```
but i think character set should be added in vokuro config

**Comment by sergeyklay** [comment]
@ch3k1 Actually I agree. But we need a more universal approach for MySql, PostgreSql and SQLite.

**Pull request closed without merging**
