### PR TITLE
Added dev config to services.php and .gitignore

### PR DESCRIPTION
**Pull request by alec-w**
Following the same approach as the Invo tutorial.
A dev config file (app/config/config.dev.php) has been added to
the .gitignore. A check is done to see if this file is readable
when loading the configuration, if it is then this config is merged
with app/config/config.php.

### CODE REVIEW

**Comment by sergeyklay** [comment]
Thanks

**Comment by dschissler** [comment]
Related to this I want to make the dev tools "web tool" to be able to pop up a Vokuro setup to offer the same functionality as in the dev tools templates.  Then next on my list is to refactor Invo so that the same thing is possible.

**Comment by sergeyklay** [comment]
https://github.com/phalcon/vokuro/commit/9573515fee52aceb7873762ecc12a5dd2c9ef554

**Comment by sergeyklay** [comment]
Fixed

**Pull request merged**
